// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQg38DfCpOEkHZzJP5d7zAJkDDqJ6wBjA',
    appId: '1:797362725470:android:57e294cf57fc15f4eecacf',
    messagingSenderId: '797362725470',
    projectId: 'smarttasksmanager',
    storageBucket: 'smarttasksmanager.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqG_5TuHedA6LvnzUO8jvar3JxEGfzQ0o',
    appId: '1:797362725470:ios:a13ab8fa01766beeeecacf',
    messagingSenderId: '797362725470',
    projectId: 'smarttasksmanager',
    storageBucket: 'smarttasksmanager.appspot.com',
    iosBundleId: 'com.example.smartTasksManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQx4JA8ijNo6luCciZLcIOGcTeDqSqaxU',
    appId: '1:797362725470:web:dc631ab9ec9bd7bdeecacf',
    messagingSenderId: '797362725470',
    projectId: 'smarttasksmanager',
    authDomain: 'smarttasksmanager.firebaseapp.com',
    storageBucket: 'smarttasksmanager.appspot.com',
    measurementId: 'G-D32D4NGGC1',
  );
}
